SPHINXBUILD   = sphinx-build
SPHINXOPTS    = -W
SOURCEDIR     = .
BUILDDIR      = _build

.PHONY: html
html:
	$(SPHINXBUILD) -b html $(SOURCEDIR) $(BUILDDIR)/html $(SPHINXOPTS)
	@echo "Build finished. The HTML pages are in $(BUILDDIR)/html/."
